### ISSUE TITLE
'config' is an undefined method

### ISSUE THREAD

**Issue by ajlanghorn** [alphagov/fastly-configure#9]
Given a working user without 2FA (because of the API's inability to support 2FA, from memory) with credentials set as the `FASTLY_USER` and `FASTLY_PASS` environment variables, along with

```
✗ ruby --version
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-darwin14.0]
```

and

```
✗ bundle show
Gems included by the bundle:
  * bundler (1.12.5)
  * colorize (0.5.8)
  * curb (0.9.1)
  * curb-fu (0.6.2)
  * diffy (3.0.1)
  * fastly (1.1.0)
  * json (1.8.3)
  * rack (1.6.4)
  * rack-test (0.6.3)
  * rake (11.1.1)
```

and

```
✗ cat fastly.yaml

---
assets:
  production:
    service_id: REDACTED
```

I get the following:

```
✗ bundle exec deploy_vcl assets production
Using version: 2
bundler: failed to load command: deploy_vcl (deploy_vcl)
NameError: undefined local variable or method `config' for main:Object
  (erb):9:in `<main>'
  /Users/langhorn/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/erb.rb:850:in `eval'
  /Users/langhorn/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/erb.rb:850:in `result'
  deploy_vcl:62:in `render_vcl'
  deploy_vcl:115:in `<top (required)>'
```

The second line of that output suggests that at least some connection to the Fastly API, via their Gem, is being made, else it wouldn't know the current version deployed to the service. It looks to me like `config` isn't being declared in `deploy_vcl`, because it's from the Fastly Gem rather than from this script itself. I'm trying to work out why `config` can't be found and used if it is coming from a third-party dependency which does include it.

Downgrading to Ruby 2.0.0 using RVM also produces the same issue.

Have you seen this before? Any ideas? Happy to help debug and work on a resolution etc.

**Comment by alexmuller** [comment]
The top line of the stack trace `(erb):9:in '<main>'` makes it seem like this is because you're trying to access `config` in your VCL but it's not defined there.

**Comment by ajlanghorn** [comment]
A-ha, that might be it -- thanks @alexmuller . Out of interest, how is it consumed by ERB for GOV.UK assets, as in [this example](https://github.com/alphagov/govuk-cdn-config/blob/master/vcl_templates/assets.vcl.erb#L9)? I can't see where it gets called in.

I don't particularly want to hardcode things like the service ID (well, share key), so that's why I was looking at using config per the above approach.

**Comment by ajlanghorn** [comment]
Fixed.
